version: '3'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_PASSWORD=mysql12345
      - APP_PORT=3000
      - DB_HOST=db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql12345
      - MYSQL_DATABASE=online_store
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
